"""followers

Revision ID: 31790929d4e8
Revises: ea7b0c8438f0
Create Date: 2023-03-27 15:06:54.680743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31790929d4e8'
down_revision = 'ea7b0c8438f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
